### ISSUE TITLE
[BUG] Does not seem to be working anymore :(

### ISSUE THREAD

**Issue by Syzygianinfern0** [Correia-jpv/ChatGPT-Notification#1]
I installed the extension from the chrome webstore and it does not seem to be playing the notification sound as it used to before. I have tried to reinstall and disable all the other ChatGPT extensions that I have.

**Comment by Syzygianinfern0** [comment]
Did you get to see this @Correia-jpv

**Comment by Correia-jpv** [comment]
> Did you get to see this @Correia-jpv

Yes, it is fixed in the newest version that is already published to the chrome store
